### PR TITLE
fix support for Python 2.7

### LINKED ISSUE #258: wheel unpack command not working in version 0.32.0
The recent changes in wheel version 0.32.0 breaks the `wheel unpack` command.

The traceback:
```
Traceback (most recent call last):
  File "/var/lib/jenkins/venv/bin/wheel", line 11, in <module>
    sys.exit(main())
  File "/var/lib/jenkins/venv/local/lib/python2.7/site-packages/wheel/cli/__init__.py", line 82, in main
    args.func(args)
  File "/var/lib/jenkins/venv/local/lib/python2.7/site-packages/wheel/cli/__init__.py", line 25, in unpack_f
    unpack(args.wheelfile, args.dest)
  File "/var/lib/jenkins/venv/local/lib/python2.7/site-packages/wheel/cli/unpack.py", line 18, in unpack
    with WheelFile(path) as wf:
  File "/var/lib/jenkins/venv/local/lib/python2.7/site-packages/wheel/wheelfile.py", line 66, in __init__
    if algorithm not in hashlib.algorithms_available:
AttributeError: 'module' object has no attribute 'algorithms_available'
```

The virtual environment is clean with no new package installed on top of it.

Verified that if I downgrade wheel to 0.31.1 in the same virtual environment, the unpack command works.

### PR DESCRIPTION
**Pull request by benoit-pierre**
`hashlib.algorithms_available` was only added in 2.7.9. Fix #258.

### CODE REVIEW

File: wheel/wheelfile.py [hunk 1]
```diff
@@ -19,6 +19,20 @@
     re.VERBOSE)
 
 
+# `hashlib.algorithms_available` was added in Python 2.7.9 / 3.2.
+if hasattr(hashlib, 'algorithms_available'):
```
Comment (agronholm) [inline wheel/wheelfile.py]: Why is this code path necessary?

File: wheel/wheelfile.py [hunk 2]
```diff
@@ -63,12 +77,12 @@ def __init__(self, file, mode='r'):
                     path, hash_sum, size = line.rsplit(u',', 2)
                     if hash_sum:
                         algorithm, hash_sum = hash_sum.split(u'=')
-                        if algorithm not in hashlib.algorithms_available:
```
Comment (agronholm) [inline wheel/wheelfile.py]: If you have a working function to check availability, why did you still move the check elsewhere?

Comment (benoit-pierre) [reply wheel/wheelfile.py]: It's still done in the constructor, it's just that IMHO, in the unlikely event that `md5`,/ `sha` is unsupported, the code should still complain about PEP 427, not about the missing support.

File: wheel/wheelfile.py [hunk 3]
```diff
@@ -19,6 +19,20 @@
     re.VERBOSE)
 
 
+# `hashlib.algorithms_available` was added in Python 2.7.9 / 3.2.
+if hasattr(hashlib, 'algorithms_available'):
+    def _hashlib_has_algorithm(algorithm):
```
Comment (safiyat) [inline wheel/wheelfile.py]: Could we rather not have the attribute check inside the function itself, instead of defining two functions?
Any particular benefit of this?

**Comment by benoit-pierre** [comment]
Here is a minimal patch.

**Comment by agronholm** [comment]
@safiyat has a point – defining a function that is only ever used in one place is wasteful. It's better to do the checking inline.

**Comment by benoit-pierre** [comment]
Third try.

File: wheel/wheelfile.py [hunk 4]
```diff
@@ -63,9 +63,11 @@ def __init__(self, file, mode='r'):
                     path, hash_sum, size = line.rsplit(u',', 2)
                     if hash_sum:
                         algorithm, hash_sum = hash_sum.split(u'=')
-                        if algorithm not in hashlib.algorithms_available:
+                        try:
+                            hashlib.new(algorithm)
+                        except ValueError:
                             raise WheelError('Unsupported hash algorithm: {}'.format(algorithm))
-                        elif algorithm.lower() in {'md5', 'sha1'}:
+                        if algorithm.lower() in {'md5', 'sha1'}:
```
Comment (agronholm) [inline wheel/wheelfile.py]: Small nit: add an empty line after the try...except block. After that I'll merge.

Comment (benoit-pierre) [reply wheel/wheelfile.py]: Done.

**Comment by agronholm** [comment]
Thanks!
