### ISSUE TITLE
wheel unpack command not working in version 0.32.0 

### ISSUE THREAD

**Issue by safiyat** [pypa/wheel#258]
The recent changes in wheel version 0.32.0 breaks the `wheel unpack` command.

The traceback:
```
Traceback (most recent call last):
  File "/var/lib/jenkins/venv/bin/wheel", line 11, in <module>
    sys.exit(main())
  File "/var/lib/jenkins/venv/local/lib/python2.7/site-packages/wheel/cli/__init__.py", line 82, in main
    args.func(args)
  File "/var/lib/jenkins/venv/local/lib/python2.7/site-packages/wheel/cli/__init__.py", line 25, in unpack_f
    unpack(args.wheelfile, args.dest)
  File "/var/lib/jenkins/venv/local/lib/python2.7/site-packages/wheel/cli/unpack.py", line 18, in unpack
    with WheelFile(path) as wf:
  File "/var/lib/jenkins/venv/local/lib/python2.7/site-packages/wheel/wheelfile.py", line 66, in __init__
    if algorithm not in hashlib.algorithms_available:
AttributeError: 'module' object has no attribute 'algorithms_available'
```

The virtual environment is clean with no new package installed on top of it.

Verified that if I downgrade wheel to 0.31.1 in the same virtual environment, the unpack command works.

**Comment by benoit-pierre** [comment]
`hashlib.algorithms_available` is only available with [Python 2 starting with 2.7.9](https://docs.python.org/2/library/hashlib.html?highlight=hashlib%20algorithms_available#hashlib.algorithms_available) or [Python 3 starting with 3.2](https://docs.python.org/3/library/hashlib.html?highlight=hashlib#hashlib.algorithms_available).
Can you confirm your version of Python is <2.7.9?

**Comment by benoit-pierre** [comment]
Does it work with this patch?
```diff
 wheel/wheelfile.py | 9 +++++----
 1 file changed, 5 insertions(+), 4 deletions(-)

diff --git i/wheel/wheelfile.py w/wheel/wheelfile.py
index 4633e4f..f2807fa 100644
--- i/wheel/wheelfile.py
+++ w/wheel/wheelfile.py
@@ -63,9 +63,7 @@ def __init__(self, file, mode='r'):
                     path, hash_sum, size = line.rsplit(u',', 2)
                     if hash_sum:
                         algorithm, hash_sum = hash_sum.split(u'=')
-                        if algorithm not in hashlib.algorithms_available:
-                            raise WheelError('Unsupported hash algorithm: {}'.format(algorithm))
-                        elif algorithm.lower() in {'md5', 'sha1'}:
+                        if algorithm.lower() in {'md5', 'sha1'}:
                             raise WheelError(
                                 'Weak hash algorithm ({}) is not permitted by PEP 427'
                                 .format(algorithm))
@@ -95,7 +93,10 @@ def _update_crc(newdata, eof=None):
             algorithm, expected_hash = self._file_hashes[ef_name]
             if expected_hash is not None:
                 # Monkey patch the _update_crc method to also check for the hash from RECORD
-                running_hash = hashlib.new(algorithm)
+                try:
+                    running_hash = hashlib.new(algorithm)
+                except ValueError:
+                    raise WheelError('Unsupported hash algorithm: {}'.format(algorithm))
                 update_crc_orig, ef._update_crc = ef._update_crc, _update_crc
 
         return ef
```

**Comment by agronholm** [comment]
I did not realize that this was a new feature in a patch version of 2.7.
I will accept a PR like above to fix the problem.

**Comment by safiyat** [comment]
@benoit-pierre Yes, this patch works.

**Comment by benoit-pierre** [comment]
@agronholm: this would move the error on an unsupported hash to the open stage, is that ok?

**Comment by benoit-pierre** [comment]
Maybe the weak hash error should be moved there too, for consistency.

**Comment by agronholm** [comment]
Could we not run the test directly in `__init__()`?
